version: '3'

networks:
  inception:

services:
  nginx:
    container_name: nginx
    image: nginx
    platform: linux/amd64
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped

  mywebsite.com:
    container_name: mywebsite.com
    image: mywebsite.com
    platform: linux/amd64
    build:
      context: ./requirements/mywebsite.com
    networks:
      - inception
    expose:
      - 8000
    depends_on:
      - nginx
    restart: unless-stopped