version: '3'

networks:
  inception:

volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  wordpress_db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  
  wordpress_object_cache:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/redis

services:
  nginx:
    container_name: nginx
    image: nginx
    platform: linux/amd64
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - mywebsite.com
      - read-me-from-middle.com
      - wordpress
      - adminer
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    platform: linux/amd64
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    platform: linux/amd64
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    platform: linux/amd64
    build:
      context: ./requirements/redis
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - wordpress_object_cache:/var/lib/redis
    networks:
      - inception
    expose:
      - 6379
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    platform: linux/amd64
    build:
      context: ./requirements/adminer
    networks:
      - inception
    expose:
      - 8080
    depends_on:
      - mariadb
    restart: unless-stopped

  vsftpd:
    container_name: vsftpd
    image: vsftpd
    platform: linux/amd64
    build:
      context: ./requirements/vsftpd
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "20:20"
      - "30000-30010:30000-30010"
    depends_on:
      - wordpress
    restart: unless-stopped

  mywebsite.com:
    container_name: mywebsite.com
    image: mywebsite.com
    platform: linux/amd64
    build:
      context: ./requirements/mywebsite.com
    command: ["-p", "80"]
    networks:
      - inception
    expose:
      - 80
    restart: unless-stopped

  read-me-from-middle.com:
    container_name: read-me-from-middle.com
    image: read-me-from-middle.com
    platform: linux/amd64
    build:
      context: ./requirements/read-me-from-middle.com
    command: ["-p", "80"]
    networks:
      - inception
    expose:
      - 80
    restart: unless-stopped