version: '3'

networks:
  inception:

volumes:
  wordpress:
  wordpress_db:

services:
  nginx:
    container_name: nginx
    image: nginx
    platform: linux/amd64
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped

  mywebsite.com:
    container_name: mywebsite.com
    image: mywebsite.com
    platform: linux/amd64
    build:
      context: ./requirements/mywebsite.com
    networks:
      - inception
    expose:
      - 8000
    depends_on:
      - nginx
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    image: wordpress
    platform: linux/amd64
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - nginx
      - mariadb
    restart: unless-stopped
  
  mariadb:
    container_name: mariadb
    image: mariadb
    platform: linux/amd64
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/lib/mysql
    user: "mysql:mysql"
    networks:
      - inception
    expose:
      - 3306
    depends_on:
      - nginx
    restart: unless-stopped